# Generated by Django 4.1.7 on 2023-03-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_product_preorderdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preorderdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='preorderdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
