# Generated by Django 4.1.7 on 2023-03-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_order_preorderdate_orderitem_preorderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='download',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
