# Generated by Django 4.1.7 on 2023-04-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_order_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='numofPreorder',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
