# Generated by Django 4.1.7 on 2023-04-02 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_song_delete_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.song'),
        ),
    ]
