# Generated by Django 4.1.7 on 2023-04-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_review_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
