# Generated by Django 4.1.7 on 2023-04-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_song_image2_song_image3_song_image4_song_image5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='song',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='song',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='song',
            name='image5',
        ),
    ]
