# Generated by Django 4.1.7 on 2023-04-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_remove_song_image2_remove_song_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isBasic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='isPremium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='isBasic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='isPremium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='isBasic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='isPremium',
            field=models.BooleanField(default=False),
        ),
    ]
