# Generated by Django 4.1.7 on 2023-04-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_order_isbought_orderitem_isbought'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isBought',
            field=models.BooleanField(default=False),
        ),
    ]
