# Generated by Django 4.1.7 on 2023-04-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_product_isbought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isBought',
            field=models.BooleanField(default=True),
        ),
    ]
