# Generated by Django 4.1.7 on 2023-04-07 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_alter_order_isbought_alter_orderitem_isbought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
    ]
