# Generated by Django 4.1.7 on 2023-04-14 00:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0052_review_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='News',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='song',
            new_name='news',
        ),
    ]
