# Generated by Django 4.1.7 on 2023-04-15 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_rename_news_new_rename_news_review_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='brand',
            new_name='headline',
        ),
        migrations.RemoveField(
            model_name='new',
            name='category',
        ),
        migrations.RemoveField(
            model_name='new',
            name='countInStock',
        ),
        migrations.RemoveField(
            model_name='new',
            name='download',
        ),
        migrations.RemoveField(
            model_name='new',
            name='music',
        ),
        migrations.RemoveField(
            model_name='new',
            name='music2',
        ),
        migrations.RemoveField(
            model_name='new',
            name='music3',
        ),
        migrations.RemoveField(
            model_name='new',
            name='music4',
        ),
        migrations.RemoveField(
            model_name='new',
            name='music5',
        ),
        migrations.RemoveField(
            model_name='new',
            name='name',
        ),
        migrations.RemoveField(
            model_name='new',
            name='numofPreorder',
        ),
        migrations.RemoveField(
            model_name='new',
            name='preorderdate',
        ),
        migrations.RemoveField(
            model_name='new',
            name='title',
        ),
        migrations.RemoveField(
            model_name='new',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='new',
            name='title3',
        ),
        migrations.RemoveField(
            model_name='new',
            name='title4',
        ),
        migrations.RemoveField(
            model_name='new',
            name='title5',
        ),
        migrations.RemoveField(
            model_name='new',
            name='watch',
        ),
    ]
