# Generated by Django 4.1.7 on 2023-04-15 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_review_gaming_review_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='category',
        ),
    ]
