# Generated by Django 4.1.7 on 2023-04-15 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_remove_sport_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.new'),
        ),
    ]
