# Generated by Django 4.1.7 on 2023-04-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_alter_new__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
