# Generated by Django 4.1.7 on 2023-04-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_alter_new__id'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='category',
            field=models.CharField(blank=True, choices=[('sports', 'Sports'), ('politics', 'Politics')], max_length=50, null=True),
        ),
    ]
