# Generated by Django 4.1.7 on 2023-04-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_alter_new_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
