# Generated by Django 4.1.7 on 2023-04-18 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0066_alter_new_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='hearts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearts_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
