# Generated by Django 4.1.7 on 2023-04-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_new_hearts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='hearts',
        ),
        migrations.AddField(
            model_name='new',
            name='isHeart',
            field=models.BooleanField(default=False),
        ),
    ]
