# Generated by Django 4.1.7 on 2023-04-19 13:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0068_remove_new_hearts_new_isheart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='new',
            new_name='Profile',
        ),
    ]
