# Generated by Django 4.1.7 on 2023-04-19 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_rename_new_profile_rename_new_review_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
