# Generated by Django 4.1.7 on 2023-04-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_alter_profile_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='createdAt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
