# Generated by Django 4.1.7 on 2023-04-20 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0072_alter_profile_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartList',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('isHeart', models.BooleanField(default=False)),
                ('canMessage', models.BooleanField(default=False)),
                ('profileofuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.profile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
