# Generated by Django 4.1.7 on 2023-04-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_heartlist_headline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heartlist',
            name='headline',
        ),
        migrations.AlterField(
            model_name='heartlist',
            name='profileofuser',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
