# Generated by Django 4.1.7 on 2023-04-20 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0078_heartlist_profileofuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heartlist',
            old_name='postofuser',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='heartlist',
            name='profileofuser',
        ),
        migrations.AddField(
            model_name='heartlist',
            name='userReceiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearts_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='heartlist',
            name='whotoheart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='heartlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearts_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
