# Generated by Django 4.1.7 on 2023-04-21 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_remove_heartlist_whotoheart_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Profile',
            new_name='profile',
        ),
    ]
