# Generated by Django 4.1.7 on 2023-04-22 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_rename_profile_review_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='isHeart',
            new_name='isVerified',
        ),
    ]
